name = "alfarank-site"
compatibility_date = "2026-05-22"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "alfarank-project-requests"
database_id = "c58cbaf8-88ab-4e34-bb0a-b389a014d224"
